- name: Installer nginx sur CentOS
  yum:
    name: nginx
    state: present

- name: Démarrer et activer Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Créer le fichier index.html avec mavariable
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html


